# Changes here will be overwritten by Copier
_commit: v7.0.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: mail@sebastian.tramp.name
author_name: Sebastian Tramp
github_page: ''
project_description: yope.social youth map
project_slug: youth-map
project_type: generic
pypi: false

